kind: pipeline
name: kafka-gitops

steps:
  - name: fix-permissions
    image: supplystack/drone-permission-fix

  - name: drone-tag
    image: supplystack/drone-tag
    depends_on:
      - fix-permissions

  - name: build
    image: supplystack/drone-gradle
    depends_on:
      - fix-permissions
    settings:
      tasks:
        - build
        - test
      # options:
      # - stacktrace
      # exclude_tasks:
      # - test