kind: pipeline
name: kafka-gitops

steps:
  - name: fix-permissions
    image: supplystack/drone-permission-fix

  - name: drone-tag
    image: supplystack/drone-tag
    depends_on:
      - fix-permissions

  - name: build
    image: supplystack/drone-gradle
    depends_on:
      - fix-permissions
    settings:
      tasks:
        - build
        # - test
      # options:
      # - stacktrace
      exclude_tasks:
      - test

  - name: deploy
    depends_on:
      - build
    image: plugins/docker
    settings:
      repo: supplystack/kafka-gitops
      tags:
      - latest
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_ACCESS_TOKEN
